//app.js
App({
  onLaunch: function () {
    
    if (!wx.cloud) {
      console.error('请使用 2.2.3 或以上的基础库以使用云能力')
    } else {
      wx.cloud.init({
        traceUser: true,
      })
    }
    this.globalData = {
      
    }
    this.user_info = {
      id: 99999999,
      nickname: "张三",
      token: "abc123abc123",
      username: "张大头",
      sex: 1,
      age: 26,
      phone:""    //目前phone为调用的属性
    }
    wx.getStorage({
      key: 'bob',
      error: function (res) {
        console.log(res);
        wx.redirectTo({
          url: 'wanzhuan',
        })
      }
    })
    ///////////////////////////////
    this.orders_thing_1={
       "order_id": "138",
        "order_sn": "15638518792057241242",
         "gtype": "material", 
         "otype": "normal", 
         "seller_id": "12427", 
         "seller_name": "红包兑换",
          "buyer_id": "31030", 
          "buyer_name": "18621849512", 
          "buyer_email": "", 
          "status": "11", 
          "sign_status": "0", 
          "sign_time": null, 
          "add_time": "1563851879", 
          "payment_id": "2", 
          "payment_name": "手机支付宝", 
          "payment_code": "alipay_wap", 
          "out_trade_sn": "", 
          "pay_time": null, 
          "pay_message": "", 
          "ship_time": null, 
          "invoice_no": null, 
          "express_company": null, 
          "finished_time": null, 
          "goods_amount": "1200.00", 
          "discount": "0.00", 
          "order_amount": "1200.00", 
          "profit": "0.00", 
          "evaluation_status": "0", 
          "evaluation_time": null, 
          "anonymous": "0", 
          "postscript": "", 
          "pay_alter": "1", 
          "flag": "0", 
          "memo": "", 
          "checkout": "0", 
          "checkout_time": null, 
          "adjust_amount": "0.00", 
          "orderGoods": [{ "rec_id": "138", "order_id": "138", "goods_id": "116", "goods_name": "太阳镜男女士经典偏光太阳眼镜经典蛤蟆镜209驾驶镜墨镜", "spec_id": "459", "specification": "颜色:黑框-偏光灰片", "price": "1200.00", "quantity": "1", "goods_image": "data/files/store_12427/goods/2.png.png.thumb.png", "evaluation": "0", "comment": "", "credit_value": "0", "is_valid": "1", "shipped_evaluation": "0.00", "service_evaluation": "0.00", "goods_evaluation": "0.00", "reply_comment": null, "reply_time": null, "reply_content": null, "inviteType": "", "inviteRatio": "", "inviteUid": "0", "status": "" }], 
          "orderGift": [],
           "status_label": "等待买家付款", 
           "goods_quantities": 1 
    }
//////////////////////////////////////////
    this.orders_thing_2 = {
       "order_id": "137", 
       "order_sn": "15638515702663811242",
        "gtype": "material", 
        "otype": "normal", 
        "seller_id": "12427", 
        "seller_name": "红包兑换", 
        "buyer_id": "31030", 
        "buyer_name": "18621849512",
         "buyer_email": "",
          "status": "11",
           "sign_status": "0",
            "sign_time": null, 
            "add_time": "1563851570", 
            "payment_id": "2", 
            "payment_name": "手机支付宝", 
            "payment_code": "alipay_wap", 
            "out_trade_sn": "", 
            "pay_time": null, 
            "pay_message": "", 
            "ship_time": null,
            "invoice_no": null,
            "express_company": null,
            "finished_time": null,
            "goods_amount": "1200.00", 
            "discount": "0.00", 
            "order_amount": "1200.00", 
            "profit": "0.00", 
            "evaluation_status": "0", 
            "evaluation_time": null, 
            "anonymous": "0", 
            "postscript": "", 
            "pay_alter": "1", 
            "flag": "0", 
            "memo": "", 
            "checkout": "0", 
            "checkout_time": null, 
            "adjust_amount": "0.00", 
            "orderGoods": [{ "rec_id": "137", "order_id": "137", "goods_id": "116", "goods_name": "太阳镜男女士经典偏光太阳眼镜经典蛤蟆镜209驾驶镜墨镜", "spec_id": "459", "specification": "颜色:黑框-偏光灰片", "price": "1200.00", "quantity": "1", "goods_image": "data/files/store_12427/goods/2.png.png.thumb.png", "evaluation": "0", "comment": "", "credit_value": "0", "is_valid": "1", "shipped_evaluation": "0.00", "service_evaluation": "0.00", "goods_evaluation": "0.00", "reply_comment": null, "reply_time": null, "reply_content": null, "inviteType": "", "inviteRatio": "", "inviteUid": "0", "status": "" }],
             "orderGift": [], 
             "status_label": "等待买家付款", 
             "goods_quantities": 1 }
    //////////////////////////////////////
    this.orders_thing_3 ={
 "order_id": "136", 
 "order_sn": "15638507935844761242", 
 "gtype": "material", 
 "otype": "normal", 
 "seller_id": "12427", 
 "seller_name": "红包兑换", 
 "buyer_id": "31030", 
 "buyer_name": "18621849512", 
 "buyer_email": "", 
 "status": "11", 
 "sign_status": "0", 
 "sign_time": null, 
 "add_time": "1563850793", 
 "payment_id": "2", 
 "payment_name": "手机支付宝", 
 "payment_code": "alipay_wap", 
 "out_trade_sn": "", 
 "pay_time": null, 
 "pay_message": "", 
 "ship_time": null, 
 "invoice_no": null, 
 "express_company": null, 
 "finished_time": null, 
 "goods_amount": "1200.00", 
 "discount": "0.00", 
 "order_amount": "1200.00", 
 "profit": "0.00", 
 "evaluation_status": "0", 
 "evaluation_time": null, 
 "anonymous": "0", 
 "postscript": "", 
 "pay_alter": "0", 
 "flag": "0", 
 "memo": "", 
 "checkout": "0", 
 "checkout_time": null, 
 "adjust_amount": "0.00", 
 "orderGoods": [{ "rec_id": "136", "order_id": "136", "goods_id": "116", "goods_name": "太阳镜男女士经典偏光太阳眼镜经典蛤蟆镜209驾驶镜墨镜", "spec_id": "459", "specification": "颜色:黑框-偏光灰片", "price": "1200.00", "quantity": "1", "goods_image": "data/files/store_12427/goods/2.png.png.thumb.png", "evaluation": "0", "comment": "", "credit_value": "0", "is_valid": "1", "shipped_evaluation": "0.00", "service_evaluation": "0.00", "goods_evaluation": "0.00", "reply_comment": null, "reply_time": null, "reply_content": null, "inviteType": "", "inviteRatio": "", "inviteUid": "0", "status": "" }], 
 "orderGift": [], 
 "status_label": 
 "等待买家付款", 
 "goods_quantities": 1 
    }
///////////////////////////////////////////
    this.orders_thing_4 = {
    "order_id": "135", 
    "order_sn": "15638506820942381242", 
    "gtype": "material", 
    "otype": "normal", 
    "seller_id": "12427", 
    "seller_name": "红包兑换", 
    "buyer_id": "31030", 
    "buyer_name": "18621849512", 
    "buyer_email": "", 
    "status": "11", 
    "sign_status": "0", 
    "sign_time": null, 
    "add_time": "1563850682", 
    "payment_id": "2", 
    "payment_name": "手机支付宝", 
    "payment_code": "alipay_wap", 
    "out_trade_sn": "", 
    "pay_time": null, 
    "pay_message": "", 
    "ship_time": null, 
    "invoice_no": null, 
    "express_company": null, 
    "finished_time": null, 
    "goods_amount": "1200.00", 
    "discount": "0.00", 
    "order_amount": "1200.00", 
    "profit": "0.00", 
    "evaluation_status": "0", 
    "evaluation_time": null, 
    "anonymous": "0", 
    "postscript": "", 
    "pay_alter": "1", 
    "flag": "0", "memo": "", 
    "checkout": "0", 
    "checkout_time": null, 
    "adjust_amount": "0.00", 
    "orderGoods": [{ "rec_id": "135", "order_id": "135", "goods_id": "116", "goods_name": "太阳镜男女士经典偏光太阳眼镜经典蛤蟆镜209驾驶镜墨镜", "spec_id": "459", "specification": "颜色:黑框-偏光灰片", "price": "1200.00", "quantity": "1", "goods_image": "data/files/store_12427/goods/2.png.png.thumb.png", "evaluation": "0", "comment": "", "credit_value": "0", "is_valid": "1", "shipped_evaluation": "0.00", "service_evaluation": "0.00", "goods_evaluation": "0.00", "reply_comment": null, "reply_time": null, "reply_content": null, "inviteType": "", "inviteRatio": "", "inviteUid": "0", "status": "" }], 
     "orderGift": [],
     "status_label": "等待买家付款", 
     "goods_quantities": 1 }
/////////////////////////////////////////
    this.orders_thing_5 = {
    "order_id": "134", 
    "order_sn": "15638505384970811242", 
    "gtype": "material", 
    "otype": "normal", 
    "seller_id": "12427", 
    "seller_name": "红包兑换", 
    "buyer_id": "31030", 
    "buyer_name": "18621849512", 
    "buyer_email": "", 
    "status": "11", 
    "sign_status": "0", 
    "sign_time": null, 
    "add_time": "1563850538", 
    "payment_id": "2", 
    "payment_name": "手机支付宝", 
    "payment_code": "alipay_wap", 
    "out_trade_sn": "", 
    "pay_time": null, 
    "pay_message": "", 
    "ship_time": null, 
    "invoice_no": null, 
    "express_company": null, 
    "finished_time": null, 
    "goods_amount": "1200.00", 
    "discount": "0.00", 
    "order_amount": "1200.00", 
    "profit": "0.00", 
    "evaluation_status": "0", 
    "evaluation_time": null, 
    "anonymous": "0", 
    "postscript": "", 
    "pay_alter": "1", 
    "flag": "0", 
    "memo": "", 
    "checkout": "0", 
    "checkout_time": null, 
    "adjust_amount": "0.00", 
    "orderGoods": [{ "rec_id": "134", "order_id": "134", "goods_id": "116", "goods_name": "太阳镜男女士经典偏光太阳眼镜经典蛤蟆镜209驾驶镜墨镜", "spec_id": "459", "specification": "颜色:黑框-偏光灰片", "price": "1200.00", "quantity": "1", "goods_image": "data/files/store_12427/goods/2.png.png.thumb.png", "evaluation": "0", "comment": "", "credit_value": "0", "is_valid": "1", "shipped_evaluation": "0.00", "service_evaluation": "0.00", "goods_evaluation": "0.00", "reply_comment": null, "reply_time": null, "reply_content": null, "inviteType": "", "inviteRatio": "", "inviteUid": "0", "status": "" }],
     "orderGift": [], 
     "status_label": "等待买家付款", 
     "goods_quantities": 1 }

    ///////////////////////////////
  }
})
